export const GET_TODO_LIST = "GET_TODO_LIST";
export const GET_TODO_LIST_SUCCESS = "GET_TODO_LIST_SUCCESS";
export const GET_TODO_LIST_ERROR = "GET_TODO_LIST_ERROR";

export const UPDATE_TODO_LIST_SUCCESS = "UPDATE_TODO_LIST_SUCCESS";
export const UPDATE_TODO_LIST_ERROR = "UPDATE_TODO_LIST_ERROR";